//! A Model Context Protocol (MCP) server for the unofficial Grindr API.
//!
//! It exposes the [`grindr`](https://git.opengrind.org/open-grind/grindr.rs)
//! transport as MCP tools over stdio: log in, make authenticated requests to any
//! endpoint, and discover the API surface from the bundled OpenAPI document.
//!
//! The Grindr API sits behind Cloudflare and fingerprints clients by their TLS
//! and HTTP/2 handshake, so requests go through `grindr.rs`, which emulates the
//! Android app's fingerprint, header order and device identity.
//!
//! Tools are organised into two groups under [`tools`]: generic discovery /
//! request tools ([`tools::generic`]) and endpoint-specific convenience tools
//! ([`tools::endpoints`]).
//!
//! **For educational purposes only.** This is unofficial software, provided
//! solely for education and research into API interoperability. It is not
//! affiliated with or endorsed by Grindr. Automating access may violate
//! Grindr's Terms of Service; you are solely responsible for how you use it.

mod geohash;
mod openapi;
mod state;
mod tools;

use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use grindr::{DeviceInfo, GrindrClient, Method, RawResponse, Session};
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::*;
use rmcp::transport::stdio;
use rmcp::{tool_handler, ErrorData as McpError, ServerHandler, ServiceExt};
use serde_json::{json, Value};

// ─── Server ────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct GrindrServer {
    client: Arc<GrindrClient>,
    device: DeviceInfo,
    state_path: PathBuf,
    // Read by the code generated by #[tool_handler]; the lint can't see that.
    #[allow(dead_code)]
    tool_router: ToolRouter<GrindrServer>,
}

/// Render any serializable value as a single pretty-printed JSON text block.
fn json_result(value: Value) -> Result<CallToolResult, McpError> {
    let text = serde_json::to_string_pretty(&value)
        .unwrap_or_else(|e| format!("<failed to serialize result: {e}>"));
    Ok(CallToolResult::success(vec![Content::text(text)]))
}

impl GrindrServer {
    fn new(client: Arc<GrindrClient>, device: DeviceInfo, state_path: PathBuf) -> Self {
        Self {
            client,
            device,
            state_path,
            // Merge the two tool groups into one router.
            tool_router: Self::generic_router() + Self::endpoint_router(),
        }
    }

    /// Read the current session out of the client's session watch channel.
    fn current_session(&self) -> Option<Session> {
        self.client.session_receiver().borrow().clone()
    }

    /// Make an authenticated request, returning the raw status and body.
    async fn raw_request(
        &self,
        method: Method,
        path: &str,
        body: Option<Value>,
    ) -> Result<RawResponse, McpError> {
        self.client
            .request_authenticated_raw(method, path, body)
            .await
            .map_err(|e| McpError::internal_error(format!("request failed: {e}"), None))
    }

    /// Parse a raw response body as JSON, falling back to a text string.
    fn parse_body(resp: &RawResponse) -> Value {
        match serde_json::from_slice::<Value>(&resp.body) {
            Ok(v) => v,
            Err(_) => Value::String(String::from_utf8_lossy(&resp.body).into_owned()),
        }
    }

    /// Make an authenticated request and render it as a `{status, body}` result,
    /// surfacing the body as JSON when it parses and as text otherwise. Shared by
    /// `grindr_request` and the higher-level endpoint tools.
    async fn authenticated_request(
        &self,
        method: Method,
        path: &str,
        body: Option<Value>,
    ) -> Result<CallToolResult, McpError> {
        let resp = self.raw_request(method, path, body).await?;
        json_result(json!({
            "status": resp.status,
            "body": Self::parse_body(&resp),
        }))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for GrindrServer {
    fn get_info(&self) -> ServerInfo {
        let info = openapi::api_info();
        let instructions = format!(
            "MCP server for the unofficial Grindr API (transport: grindr.rs, which \
            emulates the Android app's TLS/HTTP2 fingerprint).\n\n\
            Workflow:\n\
            1. Call grindr_login(email, password) once (or grindr_session_status to \
            check an existing persisted session).\n\
            2. Discover endpoints with grindr_list_tags, grindr_list_endpoints and \
            grindr_describe_endpoint.\n\
            3. Call grindr_request(method, path, body?) to hit any endpoint, or use \
            a convenience tool (grindr_browse_grid, grindr_get_profile, \
            grindr_list_conversations, grindr_get_messages, grindr_send_message, \
            grindr_update_location).\n\n\
            Note: chat is sent over the websocket (grindr_send_message); the HTTP \
            chat-send endpoint does not work.\n\n\
            For educational purposes only; unofficial and not affiliated with \
            Grindr.\n\n\
            Bundled spec: {}",
            info
        );
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_instructions(instructions)
    }
}

// ─── Session persistence ───────────────────────────────────────────────────────

/// Watch the client's session and write every change (login, refresh, logout)
/// back to the state file so it survives restarts.
fn spawn_session_persistence(client: &GrindrClient, device: DeviceInfo, path: PathBuf) {
    let mut rx = client.session_receiver();
    tokio::spawn(async move {
        loop {
            let session = rx.borrow_and_update().clone();
            if let Err(e) = state::save(&path, &device, session.as_ref()) {
                tracing::warn!("failed to persist session: {e}");
            }
            if rx.changed().await.is_err() {
                break; // client dropped
            }
        }
    });
}

#[tokio::main]
async fn main() -> Result<()> {
    // Logs MUST go to stderr; stdout carries the MCP protocol.
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "grindr_mcp=info,warn".into()),
        )
        .init();

    let path = state::state_path();
    let (persisted, fresh) = state::load_or_init(&path)?;
    if fresh {
        state::save(&path, &persisted.device, persisted.session.as_ref())?;
        tracing::info!("generated new device identity at {}", path.display());
    }

    let client = GrindrClient::new(persisted.device.clone(), persisted.session.clone())?;
    spawn_session_persistence(&client, persisted.device.clone(), path.clone());

    let server = GrindrServer::new(Arc::new(client), persisted.device, path);

    tracing::info!("grindr-mcp serving on stdio");
    let service = server.serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}
